MyApp/urls.py
from django.conf.urls import url
from .views import index
from .views import about
from .views import contact
from .views import kitchen
from .views import signup
from .views import schedule
from .views import schedule_result
from .views import schedule_delete
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^about/', about, name='about'),
    url(r'^contact/', contact, name='contact'),
    url(r'^kitchen/', kitchen, name='kitchen'),
    url(r'^signup/', signup, name='signup'),
	url(r'^schedule/', schedule, name='schedule'),
	url(r'^schedule_result/', schedule_result, name='schedule_result'),
	url(r'^schedule_delete/', schedule_delete, name='schedule_delete'),]
	

MyWebsite/MyWebsite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

lab_1/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_1.views import index as index_lab1
import MyApp.urls as MyApp

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
	re_path(r'^MyApp/', include(('MyApp.urls', 'MyApp'), namespace='MyApp')),
]

MyApp/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.
class ActivitySchedule(models.Model):
	activity = models.CharField(max_length = 100)
	category = models.CharField(max_length = 100)
	place = models.CharField(max_length = 100)
	day = models.CharField(max_length = 100)
	date = models.DateField()
	hour = models.TimeField()

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

MyApp/forms.py
from django import forms

class Message_Form(forms.Form):
	error_messages = {
		'required' : 'Please fill this blank',
		}
	attrs = {
		'size': 100,
		'class': 'form-control'
	}
	activity = forms.CharField(label='Activity', required=True, widget=forms.TextInput(attrs=attrs))
	category = forms.CharField(label='Category', required=True, widget=forms.TextInput(attrs=attrs))
	place = forms.CharField(label='Place', required=True, widget=forms.TextInput(attrs=attrs))
	day = forms.CharField(label='Day', required=True, widget=forms.TextInput(attrs=attrs))
	date = forms.DateField(label='Date', required=True, widget=forms.DateInput(attrs={'type' : 'date'}))
	hour = forms.TimeField(label='Hour', required=True, widget=forms.TimeInput(attrs={'type' : 'time'}))

MyApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import ActivitySchedule
from .forms import Message_Form

response = {'author' : 'Hana Dior'}
def index(request):
    return render(request,'index.html')
def contact(request):
    return render(request,'index.html')
def about(request):
    return render(request,'about.html')
def kitchen(request):
    return render(request,'kitchen.html')
def signup(request):
    return render(request,'signup.html')
def schedule(request):
	form = Message_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['activity'] = request.POST['activity']
		response['category'] = request.POST['category']
		response['place'] = request.POST['place']
		response['day'] = request.POST['day']
		response['date'] = request.POST['date']
		response['hour'] = request.POST['hour']
		message = ActivitySchedule(activity=response['activity'], category=response['category'], place=response['place'], day=response['day'], date=response['date'], hour=response['hour'])
		message.save()
	else:
		print('The input is wrong')
	response['form_message'] = form
	html = 'fillform.html'
	return render(request, html, response)
def schedule_result(request):
	results = ActivitySchedule.objects.all()
	response['form_result'] = results
	return render(request, 'resultform.html', response)
def schedule_delete(request):
	ActivitySchedule.objects.all().delete()
	return HttpResponseRedirect("../schedule_result")

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Hana Dior' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1999, 11, 29) #TODO Implement this, format (Year, Month, Date)
npm = 1706025182 # TODO Implement this
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

MyApp/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>LittleWorld</title>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href={% static "MyApp/style.css" %}>
</head>
<body>

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class="container-fluid">
	<a class="navbar-logo rounded-circle" href=".."><img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42743592_544158646036454_4740123858613305344_n.jpg?_nc_cat=107&oh=3b780162c89fed8b3b958cace2384b5d&oe=5C235A52" style="display : inline-block" width="80" height="80"></a>
	<div class="collapse navbar-collapse" id="navbarResponsive">
		{% block content %}{% endblock %}
	</div>
	{% include 'navbar.html'%}
</div>
</nav>

<!-- Content -->
<div class="split left">
  <div class="centered">
    <img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42635985_544158369369815_1603846130989268992_n.jpg?_nc_cat=108&oh=c4256a34b01cc37483d4571b61e4ac31&oe=5C226924" alt="photo of hana">
    <h2>Dramatic.<br>Traumatic.<br>Sarcastic.</h2>
  </div>
</div>

<div class="split right">
  <div class="centered">
    <h2>As the years go by ...</h2>
    <p>
		'99 : Was born in Bogor<br>
		'05 : Entered SD Kesatuan Bogor<br>
		'11 : Entered SMPN 2 Bogor<br>
		'14 : Entered SMAN 1 Bogor<br>
		'17 : Entered University of Indonesia<br>
		'18 : Became Asian Games Volunteer
	</p>
	<h2>A little insight about me ...</h2>
	<p>
		My hometown is in Bogor<br>
		My passion are cooking and gardening.<br> 
		On this page I will be sharing with you<br>
		Secret Recipe (on Kitchen section)<br>
		I hope you can get to know me better!
	</p>
  </div>
</div>

</body>
</html>

MyApp/templates/fillform.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>LittleWorld</title>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href={% static "MyApp/style.css" %}>
</head>
<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class="container-fluid">
	<a class="navbar-logo rounded-circle" href=".."><img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42743592_544158646036454_4740123858613305344_n.jpg?_nc_cat=107&oh=3b780162c89fed8b3b958cace2384b5d&oe=5C235A52" style="display : inline-block" width="80" height="80"></a>
	<div class="collapse navbar-collapse" id="navbarResponsive">
		{% block content %}{% endblock %}
	</div>
	{% include 'navbar.html'%}
</div>
</nav>

<!-- Form Fill-->
<div class="container">
	<div class="myform">
		<h3>Create a new account</h3>
		<form method="POST" action="{ %url 'schedule' %}">
			{% csrf_token %}
			{{ form_message.as_p }}
			<button type="submit" class="btn btn-default">Submit!</button>
		</form>
	</div>
</div>
</body>
</html>

MyApp/templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>LittleWorld</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href={% static "MyApp/style.css" %}>
</head>
<body>

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class="container-fluid">
	<a class="navbar-logo rounded-circle" href=".."><img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42743592_544158646036454_4740123858613305344_n.jpg?_nc_cat=107&oh=3b780162c89fed8b3b958cace2384b5d&oe=5C235A52" style="display : inline-block" width="80" height="80"></a>
	<div class="collapse navbar-collapse" id="navbarResponsive">
		{% block content %}{% endblock %}
	</div>
	{% include 'navbar.html'%}
</div>
</nav>

<!-- Carousel -->
<div class="container-fluid">
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
			<li data-target="#myCarousel" data-slide-to="1"></li>
			<li data-target="#myCarousel" data-slide-to="2"></li>
		</ol>
		<!-- Images -->
		<div class="carousel-inner">
			<div class="carousel-caption">
					<p class="display-3">HANA DIOR</p>
					<h5 class="display-6">A Bored & Lazy Student</h5>
			</div>
			<div class="carousel-item active">
				<img class="d-block w-100" src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42708177_544158452703140_1538090851702407168_o.jpg?_nc_cat=104&oh=93ace7431c0659bea5ed8b1d7f3301cc&oe=5C5EDB8B" alt="First Slide" >
			</div>
			<div class="carousel-item">
				<img class="d-block w-100" src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42711088_544158479369804_1340322992294461440_o.jpg?_nc_cat=105&oh=2bcff22f8140ca8a1ad78480b3bd9801&oe=5C179EB4" alt="Second Slide">
			</div>
			<div class="carousel-item">
				<img class="d-block w-100" src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42596409_544158549369797_6866573484101730304_o.jpg?_nc_cat=104&oh=7f988ec4950cd35ed822de7d5050ee87&oe=5C2825E0" alt="Third Slide">
			</div>
		</div>
	</div>
</div>

<!-- leading to About Page -->
<div class="container-fluid padding">
	<div class="aboutLeader">
		<div class="col-lg-6">
			<h3>Hey! My name is Hana Dior.<br>Currently an Information System student.<br>Here to express the very of me.</h3>
		</div>
		<div class="rmbutton">
			<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-2">
				<a href="about.html">
					<button type="button" class="btn btn-outline-secondary btn-md">Read More</button>
				</a>
			</div>
		</div>
	</div>
</div>

<hr class="separator">
<!-- leading to Kitchen Page-->
<div class="container-fluid padding">
	<div class="kitchenLeader text-center">
		<div class="col-12">
			<h2>Check out my latest Secret Recipe updates!</h2>
			<figure>
				<a href="{% url 'MyApp:kitchen' %}">
					<img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42628001_544158409369811_8615032856164433920_o.jpg?_nc_cat=105&oh=553e9bb461ab81cf4a35fe2a05a9dd24&oe=5C278290" alt="pastry" class="d-block w-100"> 
				</a>
			</figure>
		</div>
	</div>
</div>
</body>

<footer>
	<div class="container-fluid padding bg-light">
		<div class="mycontact">
			<div class="row text-center padding" id="contact">
				<div class="col-12">
					<h2>Get in Touch with Me</h2>
				</div>
				<div class="col-12 social padding">
					<a href="https://www.whatsapp.com/"><img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42614791_544158589369793_2470087764113096704_n.jpg?_nc_cat=104&oh=a2312ac5a2fb23c30b58c7a6071e690f&oe=5C58CB48" width="80" height="80"></a>
					<a href="https://www.gmail.com/"><img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42604156_544158349369817_5791070341258280960_n.jpg?_nc_cat=108&oh=940aa8eb2c6956374d0ad60c74b026e8&oe=5C6085E8" width="80" height="80"></i></a>
					<a href="https://www.twitter.com/hanaadior"><img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42631216_544158526036466_4691579350800138240_n.jpg?_nc_cat=101&oh=2ee9d51dc29243716bea5609e999b1c1&oe=5C18C584" width="80" height="80"></i></a>
				</div>
			</div>
		</div>
	</div>
</footer>
</html>

MyApp/templates/kitchen.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>LittleWorld</title>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href={% static "MyApp/style.css" %}>
	
</head>
<body>

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class="container-fluid">
	<a class="navbar-logo rounded-circle" href=".."><img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42743592_544158646036454_4740123858613305344_n.jpg?_nc_cat=107&oh=3b780162c89fed8b3b958cace2384b5d&oe=5C235A52" style="display : inline-block" width="80" height="80"></a>
	<div class="collapse navbar-collapse" id="navbarResponsive">
		{% block content %}{% endblock %}
	</div>
	{% include 'navbar.html'%}
</div>
</nav>

<!-- Content -->
<div class="container-fluid">
	<div class="col-12">
		<figure>
			<a href="#">
				<img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42628001_544158409369811_8615032856164433920_o.jpg?_nc_cat=105&oh=553e9bb461ab81cf4a35fe2a05a9dd24&oe=5C278290" alt="pastry" class="d-block w-100"> 
			</a>
		</figure>
	</div>
	<div class="recipetitle col-12 text-center">
		<div class="kitchentitle">
			<h2>Secret Recipe #1</h2>
			<h2 class="display-4">SMOKED BEEF PASTRY</h2>
		</div>
		<div class="kitchencontent">
			<h4>Secret Details</h4>
			<p>
				- Pastry sheet<br>
				- Smoked beef (can be alternated<br>with chicken or saussage)<br>
				- Bolognese sauce<br>
				- Onion<br>
				- Mozarella<br>
			</p>
			<h4>What To Do</h4>
			<p>
				1. Cut the pastry into square pieces<br>
				2. Put smoked beef, onion, and mozarella inside<br>
				3. Pour bolognese sauce on top<br>
				4. Fold the pastry sheet into triangle shape<br>
				5. Put inside oven of 190°C for 30 minutes.<br>
				6. Serve the pastry<br>
			</p>
			<h4>What I LOVE About This</h4>
			<p>
				I pick this as my very first shared<br>
				Secret Recipe is because this was<br>
				the very first food that I ever made.<br>
				Completed with love, the mozarella will melt<br> 
				inside your mouth from the very first bite<br> 
				combined with special taste of<br>
				Italian Bolognese sauce.<br>
				This is perfect for your go-to food<br> 
				as it is quick to make and delicious!
			</p>
		</div>
	</div>
</div>


</body>
</html>

MyApp/templates/navbar.html
{% load static %}
{% block content %}

<ul class="navbar-nav ml-auto">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'MyApp:index' %}">Home</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'MyApp:about' %}">About</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'MyApp:kitchen' %}">Kitchen</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="..#contact">Contact</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'MyApp:signup' %}">Sign Up</a>
			</li>
</ul>
{% endblock %}

MyApp/templates/resultform.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>LittleWorld</title>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href={% static "MyApp/style.css" %}>
</head>
<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class="container-fluid">
	<a class="navbar-logo rounded-circle" href=".."><img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42743592_544158646036454_4740123858613305344_n.jpg?_nc_cat=107&oh=3b780162c89fed8b3b958cace2384b5d&oe=5C235A52" style="display : inline-block" width="80" height="80"></a>
	<div class="collapse navbar-collapse" id="navbarResponsive">
		{% block content %}{% endblock %}
	</div>
	{% include 'navbar.html'%}
</div>
</nav>

<!-- Form Result-->
<div style="margin: 5% 5%">
	<h3>Your Schedule List</h3>
	<div style = "width: 80%">
		<table class="table" border="#0000" style="width: 100%">
			<tr background-color="#ffff">
				<th style="width: 30%">Activity</th>
				<th style="width: 15%">Category</th>
				<th style="width: 15%">Place</th>
				<th style="width: 10%">Day</th>
				<th style="width: 20%">Date</th>
				<th style="width: 10%">Hour</th>
			</tr>
			{%for e in form_result%}
			<tr background-color=#ffff>
				<td>{{e.activity}}</td>
				<td>{{e.category}}</td>
				<td>{{e.place}}</td>
				<td>{{e.day}}</td>
				<td>{{e.date}}</td>
				<td>{{e.hour}}</td>
			</tr>
			{%endfor%}
		</table>
		<a href="{% url 'MyApp:schedule_delete' %}">DELETE ALL</a>
	</div>
</div>
</body>
</html>

MyApp/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>LittleWorld</title>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href={% static "MyApp/style.css" %}>
</head>
<body>

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class="container-fluid">
	<a class="navbar-logo rounded-circle" href=".."><img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/42743592_544158646036454_4740123858613305344_n.jpg?_nc_cat=107&oh=3b780162c89fed8b3b958cace2384b5d&oe=5C235A52" style="display : inline-block" width="80" height="80"></a>
	<div class="collapse navbar-collapse" id="navbarResponsive">
		{% block content %}{% endblock %}
	</div>
	{% include 'navbar.html'%}
</div>
</nav>

<div class="container">
	<div class="myform">	
		<h3>Create a new account</h3>
		<form action="/action_page.php" data-toggle="validator" role="form" >
			<div class="form-group">
				<label for="name">Full Name:</label>
				<input type="text" class="form-control" id="name" placeholder="Enter your full name here" name="name">
			</div>
			
			<div class="form-group">
				<label for="dob">Date of Birth:</label>
				<input type="date" class="form-control" id="dob" placeholder="yyyy/mm/dd" name="dob">
			</div>
			
			<div class="form-group">
				<label for="email">E-mail:</label>
				<input type="email" class="form-control" id="email" placeholder="Enter your e-mail address here" name="name">
			</div>
			
			<div class="form-group">
				<label for="username">Username:</label>
				<input type="text" class="form-control" id="username" placeholder="Enter your desired username here" name="username">
			</div>
			
			<div class="form-group">
				<label for="password">Password:</label>
				<input type="password" class="form-control" data-minlength="6" id="password" placeholder="Enter your desired password here" name="password">
			</div>
			
			<div class="form-group">
				<label for="passwordv">Password Validation:</label>
				<input type="password" class="form-control" id="passwordv" placeholder="Re-enter your desired password here" name="name">
			</div>
			
			<div class="checkbox">
				<label><input type="checkbox" value="">Remember Me</label>
			</div>
			
			<button type="button" class="btn btn-default">Submit!</button>
			
		</form>	
	</div>
</div>

</body>
</html>

lab_2/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}